apiVersion: apps/v1
kind: Deployment
metadata:
  name: bucket
  namespace: open-cluster-management-observability
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      name: bucket
  template:
    metadata:
      labels:
        name: bucket
    spec:
      containers:
      - command:
        - /bucket
        env:
        - name: BUCKET_NAME
          value: "abutcher-gcp-oidc"
        - name: CREDENTIALS_FILE_PATH
          value: "/cloud-credentials/service_account.json"
        image: quay.io/abutcher/bucket:latest
        imagePullPolicy: Always
        name: bucket
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - name: bound-sa-token
          mountPath: /var/run/secrets/openshift/serviceaccount
          readOnly: true
        - name: cloud-credentials
          mountPath: "/cloud-credentials"
      serviceAccountName: observability-thanos-store-shard
      volumes:
      - name: bound-sa-token
        projected:
          sources:
          - serviceAccountToken:
              path: token
              audience: openshift
      - name: cloud-credentials
        secret:
          secretName: cloud-credentials
